### PR TITLE
Small Updates for my screen.

### PR DESCRIPTION
**Pull request by Toksam**

### CODE REVIEW

**Comment by Toksam** [comment]
Updating for myself.

**Comment by Toksam** [comment]
OMG. Sorry, I didn't mean to try to merge with your branch. 

I am still learning Github.

**Comment by GregDMeyer** [comment]
No problem! :-) happy coding!!

**Comment by Toksam** [comment]
Haha! Thanks! And thanks for the work getting the IT8951 working! I don't
know exactly what you did (it was really hard for me to understand) but I
appreciate it. LOL.

**Pull request closed without merging**
