### PR TITLE
Moved HRDY and RESET to spi.pyx, created methods for everything

### PR DESCRIPTION
**Pull request by BackSlasher**
1. Easier method to invoke Cython compilation
2. interface.py no longer needs GPIO access, as everything moved to SPI
3. SPI has separate methods for reset, CS signaling, HRDY checks
4. Un-inlined HRDY calls, as they're not improving timing significantly

Would be happy to hear your opinion. We could definitely only merge some of these, if you'd like.

### CODE REVIEW

**Comment by GregDMeyer** [comment]
Sorry to take forever getting to this pull request---I just rewrote the backend, so these commits don't work per se, but I agree with all of the ideas! I will incorporate these ideas into the new backend (unless you want to do that before I get around to it!). Cheers

**Comment by BackSlasher** [comment]
@GregDMeyer no worries :)
In the meanwhile I decided I'm looking for a solution that allows me to connect by USB, as I'm not good enough to scale an SPI solution, and Waveshare sucks in USB support, so I'm looking elsewhere.

Your project served very well for experimenting with e-ink screens and prototyping my first solution :D

**Comment by GregDMeyer** [comment]
OK, sounds good! Thanks for the pull requests. I hope you get USB working! I was thinking about experimenting with that as well, but I agree the Waveshare USB documentation is just terrible.

**Comment by BackSlasher** [comment]
Apperantly their demo code for usb is broken and the source code is
unavailable without some nda so...

I'll try and share interesting results if I get any 🙂

**Pull request closed without merging**
